# Generated by Django 4.0.3 on 2022-05-21 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('News_Portal', '0003_remove_category_subscribers_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CatSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='News_Portal.category')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
